---
# tasks file for roles/webservers
- name: Upload application file
  copy: 
    src: ../files/index.php
    dest: "{{ path_to_app }}"
    mode: 0755

- name: Create simple info page
  copy: 
    dest: "{{ path_to_app }}/info.php"
    content: "<h1> Les informations à propos de notre serveur {{ ansible_hostname }}. ALLO </h1>"

- name: See directory contents
  command: ls -la {{ path_to_app }}
  register: dir_contents

- name: Debug directory contents
  debug:
    msg: "{{ dir_contents }}"

- name: Configure php.ini file
  lineinfile:
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=On'
  notify: Restart apache